# Generated by Django 4.0.6 on 2022-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile.svg', upload_to='users/%Y%m%d', verbose_name='프로필사진'),
        ),
    ]
