<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-08-08 11:53
=======
# Generated by Django 4.0.6 on 2022-08-08 11:56
>>>>>>> 97cb14a587127a3c8f2b8ce51432b6b4906af92d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y%m%d', verbose_name='프로필사진'),
        ),
    ]
