# Generated by Django 4.0.6 on 2022-08-02 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='설명')),
                ('keyword', models.CharField(max_length=50, verbose_name='키워드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postUser_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
