# Generated by Django 4.0.6 on 2022-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0003_recommend_recimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='추천키워드')),
            ],
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='keyword',
        ),
        migrations.AddField(
            model_name='recommend',
            name='recKeyword',
            field=models.ManyToManyField(blank=True, to='recommends.keyword'),
        ),
    ]
