# Generated by Django 4.0.6 on 2022-08-02 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumphoto', models.ImageField(blank=True, upload_to='albumphoto/', verbose_name='앨범사진')),
                ('albumvideo', models.FileField(null=True, upload_to='albumvideo/', verbose_name='앨범동영상')),
                ('albummemo', models.TextField(verbose_name='앨범메모')),
                ('albumtype', models.CharField(max_length=50, null=True, verbose_name='앨범타입')),
                ('albumlocation', models.CharField(max_length=50, null=True, verbose_name='앨범위치')),
                ('albumdate', models.CharField(max_length=50, verbose_name='앨범날짜')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='유저아이디', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
