# Generated by Django 4.0.6 on 2022-08-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumdate',
            field=models.CharField(max_length=50, null=True, verbose_name='앨범날짜'),
        ),
        migrations.AlterField(
            model_name='album',
            name='albumphoto',
            field=models.ImageField(blank=True, null=True, upload_to='albumphoto/', verbose_name='앨범사진'),
        ),
        migrations.AlterField(
            model_name='album',
            name='albumvideo',
            field=models.FileField(blank=True, null=True, upload_to='albumvideo/', verbose_name='앨범동영상'),
        ),
    ]
