# Generated by Django 4.0.6 on 2022-08-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_albumdate_alter_album_albumphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumdate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='앨범날짜'),
        ),
        migrations.AlterField(
            model_name='album',
            name='albumlocation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='앨범위치'),
        ),
        migrations.AlterField(
            model_name='album',
            name='albumtype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='앨범타입'),
        ),
    ]
