# Generated by Django 4.0.6 on 2022-08-02 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0003_alter_album_albumdate_alter_album_albumlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFor', to=settings.AUTH_USER_MODEL),
        ),
    ]
