# Generated by Django 4.0.6 on 2022-08-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_type_alter_album_albumtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumdate',
            field=models.DateField(auto_now=True, null=True, verbose_name='앨범날짜'),
        ),
    ]
