# Generated by Django 4.0.6 on 2022-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_albumlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumlocation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='앨범위치'),
        ),
    ]
