# Generated by Django 4.0.6 on 2022-08-03 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='프레임키워드')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framephoto', models.ImageField(blank=True, null=True, upload_to='framephoto/', verbose_name='프레임사진')),
                ('frametitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='프레임제목')),
                ('frameexample', models.ImageField(blank=True, null=True, upload_to='frameexample/', verbose_name='프레임예시')),
                ('framepublic', models.BooleanField(default=True)),
                ('framememo', models.TextField(verbose_name='프레임메모')),
                ('framekeyword', models.ManyToManyField(blank=True, to='framesharings.keyword')),
                ('framelikeuser', models.ManyToManyField(blank=True, related_name='likeMany', to=settings.AUTH_USER_MODEL, verbose_name='프레임좋아요수')),
                ('framesaveuser', models.ManyToManyField(blank=True, related_name='saveMany', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userframeFor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
