# Generated by Django 4.0.6 on 2022-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesharings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='framephoto',
            field=models.ImageField(blank=True, default=None, upload_to='framephoto/', verbose_name='프레임사진'),
        ),
    ]
