# Generated by Django 4.0.6 on 2022-08-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesharings', '0003_frame_framelikedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='framelikedate',
            field=models.TextField(blank=True, null=True, verbose_name='프레임메모'),
        ),
    ]
