# Generated by Django 4.0.6 on 2022-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framesharings', '0005_frame_frameweeklike_alter_frame_framelikedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='framelikedate',
            field=models.TextField(blank=True, default='null', null=True, verbose_name='좋아요날짜'),
        ),
    ]
