# Generated by Django 4.0.6 on 2022-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lifefourcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifephotourl', models.URLField()),
                ('lifecontext', models.CharField(max_length=100)),
                ('lifeid', models.CharField(max_length=50)),
            ],
        ),
    ]
