# Generated by Django 4.0.6 on 2022-08-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lifefourcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifephotourl', models.URLField()),
                ('lifecontext', models.CharField(max_length=100, null=True)),
                ('lifeid', models.CharField(max_length=50)),
                ('lifepagename', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signaturephotourl', models.URLField(blank=True, null=True)),
                ('signaturephoto', models.URLField(blank=True, null=True)),
                ('signatureurl', models.URLField(blank=True, null=True)),
                ('signaturephotoinfo', models.CharField(blank=True, max_length=100, null=True)),
                ('signatureid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
