# Generated by Django 4.0.6 on 2022-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitedframes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifefourcut',
            name='lifepagename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
