# Generated by Django 4.0.6 on 2022-08-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitedframes', '0002_lifefourcut_lifepagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifefourcut',
            name='lifecontext',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
