# Generated by Django 4.0.6 on 2022-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitedframes', '0003_signature_signaturephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photoism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoismphotourl', models.URLField(blank=True, null=True)),
                ('photoismphoto', models.URLField(blank=True, null=True)),
                ('photoismurl', models.URLField(blank=True, null=True)),
                ('photoismphotoinfo', models.CharField(blank=True, max_length=100, null=True)),
                ('photoismid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
